branches:
  - dev/*
  - feature/*
  - hotfix/*
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/npm"
  - "@semantic-release/exec"
  - "@semantic-release/git"